module.exports = {
  SUCCESSFUL: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  UNAUTHORIZED: 401,
  NO_TOKEN: 'Please add authentication token',
  UNAUTHORIZED_MSG: 'Invalid Credentials, Please use correct email & password combination',
  OLD_PASSWORD_MSG: 'Please enter a valid old password',
  REGISTER_MSG: 'Registered successfully',
  LOGIN_MSG: 'Logged in successfully',
  LOGOUT_MSG: 'Logged out successfully',
  NOT_FOUND_MSG: 'Not found',
  FORGOT_PASSWORD: 'Reset password link sent successfully to your email address',
  CHANGE_PASSWORD: 'Password changed successfully',
  ADMIN_NOT_FOUND: 'Admin not found',
  ADMIN_DETAILS: 'Admin details',
  ADMIN_STATUS_DELETE: 'Admin deleted successfully',
  ADMIN_EMAIL_ALREADY_EXISTS: 'The admin email already exists. Please use a different email',
  ADMIN_UPDATE: 'Admin information updated successfully',
  ADMIN_CREATE: 'Admin created successfully',
};